name: simple_form_field
description: "Wrapper around TextFormField, Bloc and CachedNetworkImage and SVG images"
version: 0.0.7
homepage: https://github.com/basnetjiten/simple_form_field

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0

  #Gradient UI
  gradient_borders: ^1.0.1
  simple_gradient_text: ^1.3.0

  #data models
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  #state management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  fpdart: ^1.1.1

  flutter_svg: 2.2.0
  cached_network_image: 3.4.1
  shimmer: 3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  #generators
  build_runner: ^2.7.1

  json_serializable: ^6.11.0
  freezed: ^3.2.0


flutter:
