name: simple_form_field
description: "Wrapper around TextFormField"
version: 0.0.2
homepage: https://github.com/basnetjiten/simple_form_field

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2


flutter:
